config/routes.rb
Rails.application.routes.draw do



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get 'pages/index'
  root "boards#index"

   get "/about", to: "pages#about"
   get "/pricing", to: "pages#pricing"
   get "/payment", to: "pages#payment"
   post "/checkout", to: "pages#checkout"
  # root 'pages#index'


  namespace :api do
    namespace :v2 do
      resources :boards, only: [:index]
    end
  end


  resources :favorites, only: [:index]

  # get "/hello.php", to: "pages#php"

  resources :boards do
    # resources :posts, only: [:index, :new, :create]
    member do
      post :favorite
      put :hide
    end

    member do
      put :hide
    end

    resources :posts, shallow: true do
     resources :comments, shallow: true, only: [:create]
   end
  end

  # , param: :permalink

  resources :users, only: [:create] do
    # member do 會有id
    #   get :profile
    # end
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out
    end
  end
  #path:

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # resources :posts, except: [:index, :new, :create]

end

app/views/shared/frontend/_navbar.html.erb
<ul class="navi">
    <% if current_user %>
      <li><%= current_user.account %></li>
      <li><%= link_to "登出", sign_out_users_path, method: 'delete' %></li>
    <% else %>
      <li><%= link_to "登入", sign_in_users_path %></li>
      <li><%= link_to "註冊", sign_up_users_path %></li>

    <% end %>
</ul>

app/views/shared/frontend/_notice.html.erb
  <%= notice %>