config/routes.rb
Rails.application.routes.draw do



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get 'pages/index'
  root "boards#index"

   get "/about", to: "pages#about"
   get "/pricing", to: "pages#pricing"
   get "/payment", to: "pages#payment"
   post "/checkout", to: "pages#checkout"
  # root 'pages#index'


  namespace :api do
    namespace :v2 do
      resources :boards, only: [:index]
    end
  end


  resources :favorites, only: [:index]

  # get "/hello.php", to: "pages#php"

  resources :boards do
    # resources :posts, only: [:index, :new, :create]
    member do
      post :favorite
      put :hide
    end

    member do
      put :hide
    end

    resources :posts, shallow: true do
     resources :comments, shallow: true, only: [:create]
   end
  end

  # , param: :permalink

  resources :users, only: [:create] do
    # member do 會有id
    #   get :profile
    # end
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out
    end
  end
  #path:

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # resources :posts, except: [:index, :new, :create]

end

app/models/user.rb
class User < ApplicationRecord

  validates :account, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  before_create :encrypt_password
  has_many :comments

  has_many :board_masters
  has_many :posts
  has_many :boards, through: :board_masters
  has_many :favorite_boards
  has_many :favorited_boards, through: :favorite_boards, source: :board


  def self.login(option)
    if option[:account] && option[:password]
      find_by(account: option[:account],
      password: Digest::SHA1.hexdigest('x'+option[:password]+'y'))

      else

      end
    end


    def toggle_favorite_board(b)
       if favorited_boards.exists?(b.id)
         favorited_boards.destroy(b)
       else
         favorited_boards << b
       end
    end
      # User.login

      private
      def encrypt_password
        self.password = bigbang(self.password)
      end

      def bigbang(string)
        string = "x" + string + "y"
        Digest::SHA1.hexdigest(string)
      end
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def sign_in
    @user = User.new
  end

  def login
   user = User.login(user_params)

   if user
     sign_in_user(user)
     redirect_to boards_path, notice: "成功登入"
   else
     redirect_to sign_in_users_path, notice: "請輸入正確帳號密碼"
   end
 end

  def sign_up
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # 登入
      sign_in_user(@user)
      redirect_to boards_path, notice: '會員註冊成功'
    else
      render :sign_up
    end
  end

  def sign_out
    sign_out_user
    redirect_to boards_path, notice: '登出成功'
  end


  private
  def sign_in_user(u)
    session[:user_token] = u.id
  end

  def sign_out_user
    session[:user_token] = nil
  end

  def user_params
    params.require(:user).permit(:account, :password, :email)
  end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/sign_in.html.erb
<h1>sign in</h1>
<%= form_for(@user, url: login_users_path) do |form| %>
<div class="field">
  <%= form.label :account %>
  <%= form.text_field :account, placeholder: "enter your account or email" %>
</div>
<div class="field">
  <%= form.label :password %>
  <%= form.text_field :password, placeholder: :password %>
</div>
<h1><%= form.submit "submit" %></h1>
<% end %>

app/views/users/sign_up.html.erb
<h1>sign up</h1>

<%= form_for( @user ) do |form| %>
  <div class="field">
    <%= form.label :account, "帳號" %>
    <%= form.text_field :account %>
  </div>

  <div class="field">
    <%= form.label :password, "密碼" %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :email, "信箱" %>
    <%= form.eamil_field :email %>
  </div>

  <%= form.submit "註冊帳號" %>

<% end %>