config/routes.rb
Rails.application.routes.draw do



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get 'pages/index'
  root "boards#index"

   get "/about", to: "pages#about"
   get "/pricing", to: "pages#pricing"
   get "/payment", to: "pages#payment"
   post "/checkout", to: "pages#checkout"
  # root 'pages#index'


  namespace :api do
    namespace :v2 do
      resources :boards, only: [:index]
    end
  end


  resources :favorites, only: [:index]

  # get "/hello.php", to: "pages#php"

  resources :boards do
    # resources :posts, only: [:index, :new, :create]
    member do
      post :favorite
      put :hide
    end

    member do
      put :hide
    end

    resources :posts, shallow: true do
     resources :comments, shallow: true, only: [:create]
   end
  end

  # , param: :permalink

  resources :users, only: [:create] do
    # member do 會有id
    #   get :profile
    # end
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out
    end
  end
  #path:

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # resources :posts, except: [:index, :new, :create]

end

app/models/board.rb
class Board < ApplicationRecord

acts_as_paranoid

has_many :board_masters
has_many :users, through: :board_masters

has_many :posts, dependent: :destroy

has_many :favorite_boards
has_many :favorited_users, through: :favorite_boards, source: :user



validates :title, presence: true, length: { minimum: 2 }


  def favorited_by?(u)
    favorited_users.include?(u)
  end

  include AASM

  aasm(column: 'state') do
    state :normal, initial: true
    state :hidden, :locked

    event :hide do
      transitions from: [:normal, :locked], to: :hidden
    end

    event :show do
      transitions from: :hidden, to: :locked
    end

    event :lock do
      transitions from: [:normal, :hidden], to: :locked

      after_transaction do
        puts "locked"
      end
    end

    event :unluck do
      transitions from: :locked, to: :normal
    end




  end


end

app/controllers/api/v2/boards_controller.rb
class Api::V2::BoardsController < ApplicationController
  def index
    @boards = Board.all

  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  before_action :find_board, only: [:show, :edit, :update, :destroy , :favorite, :hide]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @boards = Board.normal.page(params[:page]).per(3)
  end

  def show
    @post = @board.posts.includes(:user)
    # @favorite_or_not = current_user.favorited_boards.where(id: @board.id)
    #@board = Board.find(params[:id])
  end



  def favorite
    current_user.toggle_favorite_board(@board)

    respond_to do |format|
      format.html { redirect_to favorites_path, notice: 'OK!' }
      format.json { render json: {status: @board.favorited_by?(current_user)}}
    end
  end

  def hide
    @board.hide! if @board.may_hide?
    redirect_to boards_path, notice: '看版己隱藏'
  end

  def new
    @board = Board.new
    authorize @board, :new?
  end

  def edit
    # @board = Board.find(params[:id])
  end


  def create
    @board = Board.new(board_params)
    @board.users << current_user
    authorize @board, :create?

    if @board.save
      # flash[:notice] = "new article!"
      redirect_to boards_path, notice: "新增成功"
      # OK
    else
      render :new
      # NG
    end
    # Board.create(title: params[:title], intro: params[:intro])
    # redirect_to "/"
  end

  def update
    # @board = Board.find(params[:id])
    if @board.update(board_params)
      redirect_to boards_path, notice: "更新成功"
    else
      render :edit
    end
  end

  def destroy
    # @board = Board.find(params[:id])
    @board.destroy
    redirect_to boards_path
  end

  private

  def find_board
    @board = Board.normal.find(params[:id])
  end




  def board_params
    params.require(:board).permit(:title, :intro)
  end

  def require_user_sign_in
    redirect_to root_path, notice: "請登入會員" if not user_sign_in?
  end

end

app/helpers/api/v2/boards_helper.rb
module Api::V2::BoardsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
  def display_bm(board)
    if board.users.count == 0
      "徵求中～"
    else
      board.users.map { |user| user.account }.join("/")
    end
  end
end

app/views/boards/_form.html.erb
<% if @board.errors.any?  %>
  <ul>
    <% @board.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>



<%= form_for(@board) do |f| %>

<div class="field">
  <%= f.label :title, "board name:" %>
  <%= f.text_field :title %>
</div>

<div class="field">
  <%= f.label :intro, "board description:" %>
  <%= f.text_area :intro %>
</div>

<%= f.submit "submit" %>
<% end %>
<h1> <%= link_to "back", boards_path %> </h1>

app/views/boards/edit.html.erb
<h1>edit new board</h1>
<%= render 'form', board: @board %>

app/views/boards/index.html.erb
<!-- <div id="hello">
<App></App>
<Ad></Ad>
</div>


<div id="board">
<Board></Board>
</div> -->


<h1>首頁看板</h1>

<%= link_to "新增看版", new_board_path if policy(:board).create? %>
<h1><%= link_to "favorite", favorites_path %></h1>
<!-- <a href="<%= new_board_path %>"> 新增看板 </a> -->


<ul>
  <% @boards.each do |board| %>
  <div class="field">
    <li>
      <%= link_to board.title, board_path(board) %>
      <%= link_to "edit", edit_board_path(board) %>
      <%= link_to "刪除", board_path(board), method: 'delete', data: { confirm: '確認刪除?'} %>
      <%= link_to "hidden", hide_board_path(board), method: 'put' %>
    </li>
  </div>
  <% end %>
</ul>

<div class="footer"><%= paginate @boards %></div>

app/views/boards/new.html.erb
<h1>create new board</h1>
<%= render 'form', board: @board %>
<!-- <a href="<%= new_board_path %>"> 新增看板 </a> -->
<!-- <form action="/boards" method="post">
  <label for="title"> 看板的名稱 : </label>
  <input type="text" name="title" id="title">
  <label for="intro"> 看板的名稱: </label>
  <textarea name="intro" id="intro"></textarea>
  <input type="submit" value="送出">
</form> -->

app/views/boards/show.html.erb
<h1> <%= @board.title %>board </h1>


<h1><%= link_to "favorite", favorites_path %></h1>

<h1 data-controller="heart" data-heart-board="<%= @board.id %>">
  <button data-action="click->heart#favorite">
     <% if @board.favorited_by?(current_user) %>
       <i class="fas fa-heart" data-target="heart.heart"></i>
     <% else %>
       <i class="far fa-heart" data-target="heart.heart"></i>
     <% end %>
   </button>
</h1>

<h2>版主 <%= display_bm(@board) %> </h2>
<h2><%= link_to "add post", new_board_post_path(@board) %></h2>

<% @board.posts.each do |post| %>

<div class= "field">
<%= post.display_username %>
<%= link_to post.title , post_path(post)%>
<%= link_to "edit", edit_post_path(post) %>
</div>
<% end %>

<h1> <%= link_to "首頁", boards_path %> </h1>