config/routes.rb
Rails.application.routes.draw do



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get 'pages/index'
  root "boards#index"

   get "/about", to: "pages#about"
   get "/pricing", to: "pages#pricing"
   get "/payment", to: "pages#payment"
   post "/checkout", to: "pages#checkout"
  # root 'pages#index'


  namespace :api do
    namespace :v2 do
      resources :boards, only: [:index]
    end
  end


  resources :favorites, only: [:index]

  # get "/hello.php", to: "pages#php"

  resources :boards do
    # resources :posts, only: [:index, :new, :create]
    member do
      post :favorite
      put :hide
    end

    member do
      put :hide
    end

    resources :posts, shallow: true do
     resources :comments, shallow: true, only: [:create]
   end
  end

  # , param: :permalink

  resources :users, only: [:create] do
    # member do 會有id
    #   get :profile
    # end
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out
    end
  end
  #path:

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # resources :posts, except: [:index, :new, :create]

end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :hello
  belongs_to :board
  belongs_to :user
  has_many :comments
  validates :title, presence: true
  validates :serial, uniqueness: true
  before_create  :create_serial
  has_one_attached :photo
  # before_create :generate_permalink

  # def to_param
  #    self.permalink
  #  end

  def display_username
    if user.nil?
       "未知"
     else
       user.account
     end
  end


  private

  def create_serial
    self.serial = serial_generator(10)
  end

  def serial_generator(n)
    a = [*'a'..'z',*'A'..'Z',*0..9].sample(n).join
  end

  def generate_permalink
     self.permalink = SecureRandom.hex(8)
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :find_board, only: [:new , :create]
 before_action :authenticate_user!, except: [:show]

  def new
    @post = @board.posts.new
  end

  def show
     @post = Post.find(params[:id])
     @comment = @post.comments.new
     @comments = @post.comments.order(id: :desc)
  end

  def edit
   @post = current_user.posts.find(params[:id])

   unless @post.exist
     redirect_to root_path, notice: '沒有權限'
   end
 end


  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: '文章更新成功'
    else
      render :edit
    end
  end


  def create
    @post = @board.posts.new(post_params)

    if @post.save

      # SendmailJob.set(wait: 10.seconds).perform_later(@post)
      redirect_to @board, notice: "add new post!"
    else
      render 'new'
    end
  end

  def edit
   @post = current_user.posts.find(params[:id])
  end

 def update
   @post = current_user.posts.find(params[:id])
   if @post.update(post_params)
     redirect_to @post, notice: '文章更新成功'
   else
     render :edit
   end
 end




private
def find_board
  @board = Board.find(params[:board_id])
end



def post_params
params.require(:post).permit(:title , :content, :photo).merge(user: current_user)
end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>編輯文章</h1>

<%= form_with(model: @post, local: true) do |form| %>

  <div class="field">
    <%= form.label :title, "標題" %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content, "內文" %>
    <%= form.text_area :content %>
  </div>

  <%= form.submit %>
<% end %>

app/views/posts/index.html.erb
1123213

app/views/posts/new.html.erb
<% if @post.errors.any?  %>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<h1>add new post</h1>


<%= form_with(model: @post, url: board_posts_path, local: true) do |p| %>

<div class="field">
  <%= p.label :title, "title" %>
  <%= p.text_field :title %>
</div>

<div class="field">
  <%= p.label :content, "content" %>
  <%= p.text_area :content %>
</div>


<div class="field">
  <%= p.label :hello, "內文" %>
  <%= p.rich_text_area :hello %>
</div>


<div class="field">
  <%= p.label :photo, "upload" %>
  <%= p.file_field :photo %>
</div>

<%= p.submit "submit" %>
<% end %>

<%= link_to "back", boards_path %>

app/views/posts/show.html.erb
<section class="post">


  <ul class="header">
    <li>
      <div>
        <span>作者</span>
        <span><%= @post.display_username %></span>
      </div>
      <div>
        <span>看板</span>
        <span><%= @post.board.title %></span>
      </div>
    </li>
    <li>
      <span>標題</span>
      <span><%= @post.title %></span>
    </li>
    <li>
      <span>時間</span>
      <span><%= @post.created_at %></span>
    </li>
  </ul>
  <hr>


  <p><%= @post.content %></p>
  <%= image_tag @post.photo.variant(resize_to_limit: [300, 300]) if @post.photo.attached? %>
    <hr>
    <ul>
      <% @comments.each do |comment| %>
      <li><%= comment.content %></li>
      <% end %>
    </ul>

    <div class="field">
      <h2>leave comments!</h2>
      <%= form_with(model: @comment, url: post_comments_path(@post)) do |form| %>
      <%= form.text_field :content %>
      <%= form.submit "送出" %>
      <% end %>

      <%= link_to "back to board", board_path(@post.board) %>
    </div>



</section>